title: a.rehman
description: Digital Resilience & 'Ilm
baseurl: "" 
url: "http://127.0.0.1:4000"

# Permalink Fix: This ensures about.md renders at /about/
permalink: /:title/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"