title: a.rehman
description: Digital Resilience & 'Ilm
baseurl: "" # Keep this empty if using a custom domain or username.github.io
url: "https://arehman-dev.github.io" # Your production URL

# Permalink Fix: This ensures about.md renders at /about/
permalink: /:title/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"